#!/www/server/panel/pyenv/bin/python
#coding: utf-8
# +-------------------------------------------------------------------
# | AdCtira灯塔Linux面板
# +-------------------------------------------------------------------
# | Copyright (c) 2015-2099 AdCtira软件(http://www.adcitra.cn) All rights reserved.
# +-------------------------------------------------------------------
# | Author: AdCtira Team
# +-------------------------------------------------------------------

import os,sys
os.chdir('/www/server/panel')
import task
task.main()
